export const certificationSections = [
  {
    id: "soc2",
    title: "SOC 2 (Type I & II)",
    intro: "SOC 2 is now a table stakes attestation for organizations looking to demonstrate sophisticated, mature cybersecurity and privacy practices to North American enterprise buyers.",
    evaluation: "3FACTOR evaluates your evidence against the five Trust Services Criteria—Security, Availability, Processing Integrity, Confidentiality, and Privacy—with surgical rigor.",
    benefitsLabel: "The benefits of a SOC 2 report:",
    benefits: [
      "Demonstrates a commitment to data privacy and executive-level governance.",
      "Ends the \"Procurement Roadblock\" where contracts stall during security reviews.",
      "Creates year-over-year benchmarking data for continued monitoring.",
      "Ensures partner relationships stay compliant and secure.",
    ],
    services: ["SOC 2 Readiness Assessment", "SOC 2 Type 1 Report", "SOC 2 Type 2 Report"],
    spotlightTitle: "Service Spotlight: Readiness Assessment",
    spotlightBody: "Our readiness assessment identifies \"revenue-blocking gaps\" in your controls to provide opportunity for remediation prior to the official audit. This bridges the knowledge gap and ensures you grasp how SOC attestation impacts the broader business.",
  },
  {
    id: "iso27001",
    title: "ISO 27001",
    intro: "ISO 27001 is the universal language of security required to compete in global enterprise markets and win high-value international tenders.",
    evaluation: "We evaluate your Information Security Management System (ISMS) across people, processes, and technical controls to ensure a systematic approach to risk.",
    benefitsLabel: "The benefits of ISO 27001:",
    benefits: [
      "Unlocks Global Revenue by satisfying international security requirements.",
      "Accelerates Sales Cycles by providing a single, globally recognized proof of security.",
      "Protects Enterprise Value through a proactive, board-level commitment to risk management.",
    ],
    services: ["Gap Discovery", "ISMS Program Architecture", "Internal Audit Readiness"],
  },
  {
    id: "pci",
    title: "PCI DSS",
    intro: "PCI DSS is the lifeblood of organizations handling cardholder data. We help you navigate these requirements so your transaction rails stay open and your revenue stream is protected from sudden blackouts.",
    evaluation: "3FACTOR evaluates your Cardholder Data Environment (CDE) against the 12 rigorous requirements to ensure sensitive data is protected at every touchpoint.",
    benefitsLabel: "The benefits of PCI DSS:",
    benefits: [
      "Prevents Revenue Blackouts by avoiding merchant account suspensions.",
      "Reduces Financial Liability from non-compliance fines and breach-related costs.",
      "Optimizes Architecture to reduce audit scope and future operational friction.",
    ],
    services: ["PCI Report on Compliance (RoC)", "SAQ Support", "Network Segmentation Validation"],
  },
  {
    id: "sox",
    title: "SOX — Financial Integrity",
    intro: "For publicly traded companies or those preparing for an IPO, SOX compliance is the foundation of financial integrity. We ensure your IT General Controls (ITGC) meet the highest standards of accuracy.",
    evaluation: "We evaluate the controls surrounding your financial reporting systems to ensure data integrity, authorized access, and auditability.",
    benefitsLabel: "The benefits of SOX Compliance:",
    benefits: [
      "Restores Investor Trust through verified financial reporting accuracy.",
      "Strengthens Corporate Governance at the board and executive level.",
    ],
    services: ["ITGC Gap Analysis", "Control Testing & Validation", "IPO Readiness"],
  },
  {
    id: "gdpr",
    title: "GDPR — Global Privacy",
    intro: "GDPR is the world's most stringent privacy mandate. We move you beyond \"cookies and consent\" to true data protection by design, ensuring you can operate safely in the European market.",
    evaluation: "We evaluate your data processing activities, consent mechanisms, and \"Right to be Forgotten\" protocols against EU standards.",
    benefitsLabel: "The benefits of GDPR Alignment:",
    benefits: [
      "Avoids heavy non-compliance fines (up to 4% of global turnover).",
      "Builds deep trust with European customers who prioritize data sovereignty.",
    ],
    services: ["Data Protection Impact Assessments (DPIA)", "Privacy Program Design"],
  },
  {
    id: "nis2",
    title: "NIS2 & DORA — EU Regulatory Resilience",
    intro: "These new EU mandates represent an aggressive new era of enforcement for infrastructure and finance, introducing personal liability for directors and heavy fines. We help you future-proof your business by proving resilience.",
    evaluation: "3FACTOR determines your \"in-scope\" status and aligns your incident response and supply chain strategies with aggressive new EU enforcement powers.",
    benefitsLabel: "The benefits of NIS2/DORA:",
    benefits: [
      "Protects against fines of up to €10M or 2% of global turnover.",
      "Ensures directors can demonstrate \"due care\" to avoid personal legal exposure.",
      "Maintains your \"license to operate\" in key European financial and utility markets.",
    ],
    services: ["Scope & Applicability Analysis", "Resilience Roadmap", "Third-Party Risk Audit"],
  },
  {
    id: "nist",
    title: "NIST Frameworks",
    intro: "NIST represents the blueprint for institutional resilience. We translate these complex federal controls into actionable business strategy for your leadership.",
    evaluation: "We benchmark your current posture against core functions: Identify, Protect, Detect, Respond, and Recover.",
    services: ["CSF Maturity Assessments", "NIST 800-53/171 Gap Analysis"],
  },
  {
    id: "fedramp",
    title: "FedRAMP",
    intro: "FedRAMP is the most rigorous security authorization in the world, required for any Cloud Service Provider looking to sell to the U.S. Federal Government.",
    evaluation: "We guide you through the intense documentation and testing requirements of the FedRAMP PMO and sponsoring agencies.",
    benefitsLabel: "The benefits:",
    benefits: [
      "Unlocks multi-million dollar federal contracts and provides the highest mark of security for private enterprise.",
    ],
    services: ["Readiness Assessments (RAR)", "System Security Plan (SSP) Development"],
  },
  {
    id: "healthcare",
    title: "HIPAA & HITRUST",
    intro: "In healthcare, a single leak is a company-ending event. We help healthcare tech firms move from \"self-assessed\" to \"elite certified,\" ensuring patient data is unshakeable.",
    benefitsLabel: "The benefits:",
    benefits: [
      "Meets high-security hurdles of healthcare payers while reducing audit fatigue through the HITRUST \"assess once, report many\" model.",
    ],
    services: ["HITRUST Readiness", "HIPAA Security Rule Assessment"],
  },
  {
    id: "cmmc",
    title: "CMMC",
    intro: "CMMC is the mandatory gateway for organizations looking to secure their place in the Department of Defense (DoD) supply chain.",
    evaluation: "We evaluate your maturity to protect Controlled Unclassified Information (CUI) and meet the requirements of the world's largest buyer.",
    benefitsLabel: "The benefits:",
    benefits: [
      "Unlocks multi-million dollar DoD contracts and protects your organization from being the weak link in national security.",
    ],
    services: [],
  },
];
