export const certificationSections = [
  {
    id: "soc2",
    title: "SOC 2 (Type I & II)",
    intro: "SOC 2, once a competitive differentiator, is now a table stakes attestation for organizations looking to demonstrate mature cybersecurity and privacy practices. As architects who have secured 9 of the top 10 Cloud Service Providers, 3FACTOR provides the elite technical guidance needed to bolster this foundational level of security.",
    evaluation: "3FACTOR evaluates your evidence against the five Trust Services Criteria—Security, Availability, Processing Integrity, Confidentiality, and Privacy—with rigor and technical depth.",
    benefits: [
      "Demonstrates a commitment to data privacy and cybersecurity compliance.",
      "Builds a strong foundation for a scalable security program.",
      "Creates benchmarking data for continued governance and monitoring.",
      "Ensures customer and partner relationships stay compliant and secure.",
    ],
    services: ["SOC 2 Readiness Assessment", "SOC 2 Type 1 Report", "SOC 2 Type 2 Report"],
    spotlightTitle: "Service Spotlight: Readiness Assessment",
    spotlightBody: "Our Readiness Assessment evaluates your controls to identify gaps and provides opportunities for remediation prior to the official audit. This is essential for organizations undergoing a SOC audit for the first time to bridge knowledge gaps and understand how attestation impacts the broader business.",
  },
  {
    id: "iso27001",
    title: "ISO 27001",
    intro: "ISO 27001 is the universal language of security required to compete in global enterprise markets. For organizations looking to expand internationally, it is the gold standard for proving a systematic approach to managing sensitive company information.",
    evaluation: "We evaluate your Information Security Management System (ISMS) across 114 controls (Annex A) and the core clauses of the standard, focusing on risk management and continuous improvement.",
    benefits: [
      "Unlocks global revenue by satisfying international security requirements.",
      "Streamlines sales cycles by replacing lengthy security questionnaires.",
      "Protects enterprise value through a proactive, board-level commitment to risk.",
      "Provides a flexible foundation that maps easily to other frameworks.",
    ],
    services: ["ISO 27001 Gap Analysis", "ISMS Implementation Support", "Internal Audit"],
    spotlightTitle: "Service Spotlight: Gap Analysis",
    spotlightBody: "Our Gap Analysis provides a comprehensive \"look under the hood\" of your current security posture. We identify exactly where your existing policies or technical controls fall short of the standard, providing a clear roadmap to certification.",
  },
  {
    id: "pci",
    title: "PCI DSS",
    intro: "PCI DSS is the essential standard for any organization handling cardholder data. In high-velocity transaction environments, it is the shield that protects your revenue stream and ensures your payment rails stay open.",
    evaluation: "3FACTOR evaluates your Cardholder Data Environment (CDE) against the 12 rigorous requirements to ensure data is protected at every touchpoint.",
    benefits: [
      "Prevents revenue blackouts by avoiding merchant account suspensions.",
      "Reduces financial liability from non-compliance fines and breach costs.",
      "Builds consumer trust by signaling elite care for financial data.",
      "Optimizes payment architecture to reduce audit scope and cost.",
    ],
    services: ["PCI Report on Compliance (RoC)", "SAQ Guidance", "Network Segmentation Validation"],
    spotlightTitle: "Service Spotlight: Segmentation Validation",
    spotlightBody: "We help you define and validate your CDE boundaries. By properly isolating systems that touch card data, we significantly reduce your audit burden and lower your overall risk profile.",
  },
  {
    id: "fedramp",
    title: "FedRAMP & CMMC",
    intro: "For cloud providers and defense contractors, compliance is the literal \"License to Operate.\" Whether you are pursuing a federal ATO or a DoD contract, these frameworks are the gateway to the world's largest buyer.",
    evaluation: "We benchmark your environment against NIST 800-53 (FedRAMP) or NIST 800-171 (CMMC) controls to ensure Controlled Unclassified Information (CUI) is protected.",
    benefits: [
      "Unlocks multi-million dollar federal and Department of Defense contracts.",
      "Provides a defensible security posture that outpaces competitors.",
      "Moves security from a manual burden to an institutional strength.",
      "Protects the integrity of the national security supply chain.",
    ],
    services: ["FedRAMP Readiness Assessment (RAR)", "CMMC Gap Assessment", "PO&AM Development"],
    spotlightTitle: "Service Spotlight: FedRAMP RAR",
    spotlightBody: "The Readiness Assessment is a mandatory \"dress rehearsal.\" We evaluate your technical capabilities and documentation to ensure you are truly prepared for agency sponsorship.",
  },
  {
    id: "nis2",
    title: "NIS2 & DORA",
    intro: "The EU's new mandates introduce personal liability for directors and heavy fines for non-compliance. For service providers in critical sectors or finance, these represent a fundamental shift in regulatory enforcement.",
    evaluation: "3FACTOR determines your \"in-scope\" status and aligns your incident response and supply chain strategies with European mandates.",
    benefits: [
      "Protects the organization from fines of up to 2% of global turnover.",
      "Ensures leadership can demonstrate \"due care\" to avoid personal liability.",
      "Hardens operations against systemic risks in critical infrastructure.",
      "Ensures your \"license to operate\" in the EU is never called into question.",
    ],
    services: ["Scope & Applicability Analysis", "Resilience Roadmap", "Third-Party Risk Audit"],
    spotlightTitle: "Service Spotlight: Scope & Applicability Analysis",
    spotlightBody: "We determine whether your organization falls within NIS2 or DORA scope, map your obligations, and build a practical roadmap that protects leadership from personal liability exposure.",
  },
];
